name: Build StandardNotes/web docker image and push to ghcr.io

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'StandardNotes/web''s version'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: STANDARDNOTES_WEB_VERSION=${{ inputs.version }}
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/standardnotes-web:${{ inputs.version }}
